<a href="https://colab.research.google.com/github/ModestGoblin/movie-analysis-/blob/main/movie_analysis_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('movie.csv', engine='python')

In [3]:
data.tail(11)

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
9826,2015-01-20,The Atticus Institute,"In the early 1970s, Dr. Henry West creates an ...",13.364,255,5.7,en,Horror,https://image.tmdb.org/t/p/original/43dvapnp9D...
9827,2005-05-18,I'm in Love With My Little Sister,Yori and his twin sister Iku used to be very c...,13.360,9,5.7,ja,"Romance, Animation, Drama",https://image.tmdb.org/t/p/original/fRdxgR85XX...
9828,2013-08-23,All Is Lost,"During a solo voyage in the Indian Ocean, a ve...",13.359,1319,6.6,en,"Action, Adventure, Drama",https://image.tmdb.org/t/p/original/9cVA4oX2xH...
9829,2008-05-13,Amateur Porn Star Killer 2,Shane Ryan's sequel to the disturbing Amateur ...,13.359,14,5.4,en,"Crime, Horror",https://image.tmdb.org/t/p/original/iBmngXVhDu...
9830,1992-06-26,Unlawful Entry,"After a break-in at their house, a couple gets...",13.358,199,6.1,en,"Crime, Thriller, Mystery",https://image.tmdb.org/t/p/original/sKUk1ca6gH...
9831,1974-11-06,The Little Prince,"Based on the story by Antoine deSaint-Exupery,...",13.357,89,6.6,en,"Science Fiction, Fantasy, Family, Music",https://image.tmdb.org/t/p/original/ts0TGlxlBf...
9832,1973-10-15,Badlands,A dramatization of the Starkweather-Fugate kil...,13.357,896,7.6,en,"Drama, Crime",https://image.tmdb.org/t/p/original/z81rBzHNgi...
9833,2020-10-01,Violent Delights,A female vampire falls in love with a man she ...,13.356,8,3.5,es,Horror,https://image.tmdb.org/t/p/original/4b6HY7rud6...
9834,2016-05-06,The Offering,When young and successful reporter Jamie finds...,13.355,94,5.0,en,"Mystery, Thriller, Horror",https://image.tmdb.org/t/p/original/h4uMM1wOhz...
9835,2021-03-31,The United States vs. Billie Holiday,Billie Holiday spent much of her career being ...,13.354,152,6.7,en,"Music, Drama, History",https://image.tmdb.org/t/p/original/vEzkxuE2sJ...
9836,1984-09-23,Threads,Documentary style account of a nuclear holocau...,13.354,186,7.8,en,"War, Drama, Science Fiction",https://image.tmdb.org/t/p/original/lBhU4U9Eeh...